/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Met' at '29/04/17 16.34' with Gradle 2.14.1
 *
 * @author Met, @date 29/04/17 16.34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
